/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

import java.awt.CardLayout;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author dhafa
 */
public class ChangeProfileP extends JPanel {

    /**
     * Creates new form ChangeProfileP
     */
    private JPanel cards;
    private CardLayout cardLayout;
    private String filePath;
    private BioUserP BioMahC;
    private WelcomeP WelcomeC;
    
    public ChangeProfileP(JPanel cards, CardLayout cardLayout, BioUserP BioMahC, WelcomeP WelcomeC){
        this.BioMahC = BioMahC;
        this.WelcomeC = WelcomeC;
        this.cards = cards;
        this.cardLayout = cardLayout;
        initComponents();
        repaint();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background8 = new Background.Background();
        mainPanel8 = new javax.swing.JPanel();
        TitleCP = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelPhone = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        labelBio = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        isiNameCP = new swing.RoundTextField();
        isiEmailCP = new swing.RoundTextField();
        isiPhoneCP = new swing.RoundTextField();
        isiAddressCP = new swing.RoundTextField();
        isiBioCP = new swing.RoundTextArea();
        isiGenderCP = new swing.RoundComboBox();
        buttonSaveChanges = new swing.RoundButton();
        buttonChangeProfilePhoto = new swing.RoundButton();

        setPreferredSize(new java.awt.Dimension(700, 453));

        background8.setPic("bgUP.png");
        background8.setPreferredSize(new java.awt.Dimension(700, 453));

        mainPanel8.setOpaque(false);

        TitleCP.setBackground(new java.awt.Color(0, 0, 0));
        TitleCP.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        TitleCP.setForeground(new java.awt.Color(0, 0, 0));
        TitleCP.setText("Change Profile");

        labelName.setBackground(new java.awt.Color(0, 0, 0));
        labelName.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        labelName.setForeground(new java.awt.Color(0, 0, 0));
        labelName.setText("Full Name");

        labelEmail.setBackground(new java.awt.Color(0, 0, 0));
        labelEmail.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(0, 0, 0));
        labelEmail.setText("Email");

        labelPhone.setBackground(new java.awt.Color(0, 0, 0));
        labelPhone.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        labelPhone.setForeground(new java.awt.Color(0, 0, 0));
        labelPhone.setText("Phone");

        labelAddress.setBackground(new java.awt.Color(0, 0, 0));
        labelAddress.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        labelAddress.setForeground(new java.awt.Color(0, 0, 0));
        labelAddress.setText("Address");

        labelBio.setBackground(new java.awt.Color(0, 0, 0));
        labelBio.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        labelBio.setForeground(new java.awt.Color(0, 0, 0));
        labelBio.setText("Bio");

        labelGender.setBackground(new java.awt.Color(0, 0, 0));
        labelGender.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        labelGender.setForeground(new java.awt.Color(0, 0, 0));
        labelGender.setText("Gender");

        isiBioCP.setColumns(20);
        isiBioCP.setRows(5);

        isiGenderCP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Choose>", "Male", "Female" }));

        buttonSaveChanges.setBackground(new java.awt.Color(102, 102, 102));
        buttonSaveChanges.setForeground(new java.awt.Color(255, 255, 255));
        buttonSaveChanges.setText("Save Changes");
        buttonSaveChanges.setBackgroundColor("#5E17EB");
        buttonSaveChanges.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        buttonSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveChangesActionPerformed(evt);
            }
        });

        buttonChangeProfilePhoto.setBackground(new java.awt.Color(102, 102, 102));
        buttonChangeProfilePhoto.setForeground(new java.awt.Color(255, 255, 255));
        buttonChangeProfilePhoto.setText("Change Profile Photo");
        buttonChangeProfilePhoto.setBackgroundColor("#5271ff");
        buttonChangeProfilePhoto.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        buttonChangeProfilePhoto.setMaximumSize(new java.awt.Dimension(151, 24));
        buttonChangeProfilePhoto.setMinimumSize(new java.awt.Dimension(151, 24));
        buttonChangeProfilePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangeProfilePhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanel8Layout = new javax.swing.GroupLayout(mainPanel8);
        mainPanel8.setLayout(mainPanel8Layout);
        mainPanel8Layout.setHorizontalGroup(
            mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonSaveChanges, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(labelEmail)
                    .addComponent(TitleCP)
                    .addComponent(labelName)
                    .addComponent(labelAddress)
                    .addComponent(labelPhone)
                    .addComponent(isiNameCP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(isiEmailCP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(isiPhoneCP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(isiAddressCP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel8Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBio)
                            .addComponent(labelGender)
                            .addComponent(isiGenderCP, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isiBioCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonChangeProfilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        mainPanel8Layout.setVerticalGroup(
            mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TitleCP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanel8Layout.createSequentialGroup()
                        .addGroup(mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelName)
                            .addComponent(labelBio))
                        .addGap(7, 7, 7)
                        .addComponent(isiNameCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isiEmailCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(isiBioCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel8Layout.createSequentialGroup()
                        .addComponent(labelPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isiPhoneCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanel8Layout.createSequentialGroup()
                        .addComponent(labelGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isiGenderCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, Short.MAX_VALUE)
                .addComponent(labelAddress)
                .addGap(3, 3, 3)
                .addGroup(mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonChangeProfilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isiAddressCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonSaveChanges, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout background8Layout = new javax.swing.GroupLayout(background8);
        background8.setLayout(background8Layout);
        background8Layout.setHorizontalGroup(
            background8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background8Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(mainPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        background8Layout.setVerticalGroup(
            background8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveChangesActionPerformed
        // TODO add your handling code here:
        
        if (filePath != null){
            BioMahC.getProfilePicBU().setPic(filePath);
            WelcomeC.getProfilePicW().setPic(filePath);
        }

        updateUIComponentIfNotEmpty(isiNameCP, BioMahC.getTitleNama(), WelcomeC.getButtonName());
        updateUIComponentIfNotEmpty(isiEmailCP, BioMahC.getTitleEmailBU(), null);
        updateUIComponentIfNotEmpty(isiPhoneCP, BioMahC.getTitleNoTelpBU(), null);
        updateUIComponentIfNotEmpty(isiAddressCP, BioMahC.getTitleAlamatBU(), null);
        if (!isiBioCP.getText().equals("")){
            BioMahC.getTitleBioBU().setText(isiBioCP.getText());
        }

        isiBioCP.setText("");
        JTextField[] textFields = {isiNameCP, isiEmailCP, isiPhoneCP, isiAddressCP};

        for (JTextField textField : textFields) {
            textField.setText("");
        }
        
        isiGenderCP.setSelectedItem("<Choose>");

        cardLayout.show(cards, "BioUserC");
    }//GEN-LAST:event_buttonSaveChangesActionPerformed
    
    private void updateUIComponentIfNotEmpty(JTextField textField, JLabel label, JButton button) {
        String text = textField.getText().trim();
        if (!text.isEmpty()) {
            label.setText(text);
            if (button != null) {
                button.setText(text);
            }
        }
    }
    private void buttonChangeProfilePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangeProfilePhotoActionPerformed
        // TODO add your handling code here:

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnValue = fileChooser.showOpenDialog(this);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            filePath = selectedFile.getAbsolutePath();
        }

    }//GEN-LAST:event_buttonChangeProfilePhotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleCP;
    private Background.Background background8;
    private swing.RoundButton buttonChangeProfilePhoto;
    private swing.RoundButton buttonSaveChanges;
    private swing.RoundTextField isiAddressCP;
    private swing.RoundTextArea isiBioCP;
    private swing.RoundTextField isiEmailCP;
    private swing.RoundComboBox isiGenderCP;
    private swing.RoundTextField isiNameCP;
    private swing.RoundTextField isiPhoneCP;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelBio;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JPanel mainPanel8;
    // End of variables declaration//GEN-END:variables
}
