/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.CardLayout;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author dhafa
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public String filePath;
    public String namaL;
    public String email;
    public String uName;
    public String pass;
    public char[] CpassL;
    public String passL;
    
    public main() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginP = new javax.swing.JPanel();
        background1 = new Background.BackgroundRL();
        mainPanel1 = new javax.swing.JPanel();
        labelLogin = new javax.swing.JLabel();
        isiEmailUsernameL = new swing.TextField();
        isiPasswordL = new swing.PasswordField();
        buttonSignIn = new swing.CoolButton();
        linkL = new swing.Link1();
        RegisterP = new javax.swing.JPanel();
        background2 = new Background.BackgroundRL();
        mainPanel2 = new javax.swing.JPanel();
        labelRegis = new javax.swing.JLabel();
        isiNamaR = new swing.TextField();
        isiEmailR = new swing.TextField();
        isiUsernameR = new swing.TextField();
        isiPasswordR = new swing.TextField();
        checR = new swing.CoolCheckBox();
        buttonRegis = new swing.CoolButton();
        linkR = new swing.Link2();
        WelcomeP = new javax.swing.JPanel();
        background3 = new Background.Background();
        mainPanel3 = new javax.swing.JPanel();
        labelWelcome = new javax.swing.JLabel();
        labelSuccess = new javax.swing.JLabel();
        buttonMulaiK = new swing.RoundButton();
        buttonQuiz = new swing.RoundButton();
        linkW = new swing.Link4();
        profilePicW = new swing.RightSideProfilePic();
        buttonName = new swing.TransparentButton();
        MulaiKP = new javax.swing.JPanel();
        background4 = new Background.Background();
        mainPanel4 = new javax.swing.JPanel();
        linkLK = new swing.Link3();
        TitleKonseling = new javax.swing.JLabel();
        boxKonselor = new swing.RoundComboBox();
        boxHari = new swing.RoundComboBox();
        boxJam = new swing.RoundComboBox();
        buttonHub = new swing.RoundButton();
        BioKonP = new javax.swing.JPanel();
        background5 = new Background.Background();
        mainPanel5 = new javax.swing.JPanel();
        FeedbackP = new javax.swing.JPanel();
        background6 = new Background.Background();
        mainPanel6 = new javax.swing.JPanel();
        TitleFB = new javax.swing.JLabel();
        labelTulisFB = new javax.swing.JLabel();
        labelTopFB = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        c1 = new swing.LabelArea();
        c2 = new swing.LabelArea();
        c3 = new swing.LabelArea();
        c4 = new swing.LabelArea();
        c5 = new swing.LabelArea();
        buttonFeedback = new swing.RoundButton();
        buttonPrev = new swing.RoundButton();
        buttonNext = new swing.RoundButton();
        linkF = new swing.Link3();
        isiFB = new javax.swing.JTextArea();
        BioMahP = new javax.swing.JPanel();
        background7 = new Background.Background();
        mainPanel7 = new javax.swing.JPanel();
        profilePicBM = new swing.ProfilePic();
        TitleNama = new javax.swing.JLabel();
        buttonUbahProfil = new swing.RoundButton();
        buttonKeluarAkun = new swing.RoundButton();
        linkBM = new swing.Link3();
        labelEmailBM = new javax.swing.JLabel();
        TitleEmailBM = new javax.swing.JLabel();
        labelUserNameBM = new javax.swing.JLabel();
        TitleUNameBM = new javax.swing.JLabel();
        labelNoTelpBM = new javax.swing.JLabel();
        TitleNoTelpBM = new javax.swing.JLabel();
        labelAlamatBM = new javax.swing.JLabel();
        TitleAlamatBM = new javax.swing.JLabel();
        labelBioBM = new javax.swing.JLabel();
        TitleBioBM = new javax.swing.JTextArea();
        UbahProfilP = new javax.swing.JPanel();
        background8 = new Background.Background();
        mainPanel8 = new javax.swing.JPanel();
        TitleUP = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelNoTelp = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelBio = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        isiNamaUP = new swing.RoundTextField();
        isiEmailUP = new swing.RoundTextField();
        isiNoTelpUP = new swing.RoundTextField();
        isiAlamatUP = new swing.RoundTextField();
        isiBioUP = new swing.RoundTextArea();
        isiGenderUP = new swing.RoundComboBox();
        buttonSimpanPer = new swing.RoundButton();
        buttonUbahFoto = new swing.RoundButton();
        mpanel = new javax.swing.JPanel();
        background = new Background.Background();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        background1.setBlur(mainPanel1);
        background1.setPic("bgLogReg.jpg");

        mainPanel1.setOpaque(false);

        labelLogin.setBackground(new java.awt.Color(0, 0, 0));
        labelLogin.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        labelLogin.setForeground(new java.awt.Color(255, 255, 255));
        labelLogin.setText("YOUTHWELNESS");

        isiEmailUsernameL.setHint("Email/Username");

        isiPasswordL.setHint("Password");

        buttonSignIn.setBackground(new java.awt.Color(255, 255, 255));
        buttonSignIn.setForeground(new java.awt.Color(255, 255, 255));
        buttonSignIn.setText("Sign In");
        buttonSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignInActionPerformed(evt);
            }
        });

        linkL.setForeground(new java.awt.Color(255, 255, 255));
        linkL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanel1Layout = new javax.swing.GroupLayout(mainPanel1);
        mainPanel1.setLayout(mainPanel1Layout);
        mainPanel1Layout.setHorizontalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(labelLogin))
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(isiEmailUsernameL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(isiPasswordL, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(buttonSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(linkL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        mainPanel1Layout.setVerticalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelLogin)
                .addGap(46, 46, 46)
                .addComponent(isiEmailUsernameL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isiPasswordL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(buttonSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linkL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LoginPLayout = new javax.swing.GroupLayout(LoginP);
        LoginP.setLayout(LoginPLayout);
        LoginPLayout.setHorizontalGroup(
            LoginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LoginPLayout.setVerticalGroup(
            LoginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(LoginP, "LoginC");

        RegisterP.setPreferredSize(new java.awt.Dimension(664, 453));

        background2.setBlur(mainPanel2);
        background2.setPic("bgLogReg.jpg");
        background2.setPreferredSize(new java.awt.Dimension(665, 443));

        mainPanel2.setOpaque(false);

        labelRegis.setBackground(new java.awt.Color(0, 0, 0));
        labelRegis.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        labelRegis.setForeground(new java.awt.Color(255, 255, 255));
        labelRegis.setText("Registerasi Akun");

        isiNamaR.setHint("Nama Lengkap");

        isiEmailR.setHint("Email");

        isiUsernameR.setHint("Username");

        isiPasswordR.setHint("Password");

        buttonRegis.setBackground(new java.awt.Color(255, 255, 255));
        buttonRegis.setForeground(new java.awt.Color(255, 255, 255));
        buttonRegis.setText("Register");
        buttonRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisActionPerformed(evt);
            }
        });

        linkR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanel2Layout = new javax.swing.GroupLayout(mainPanel2);
        mainPanel2.setLayout(mainPanel2Layout);
        mainPanel2Layout.setHorizontalGroup(
            mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel2Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linkR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel2Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel2Layout.createSequentialGroup()
                        .addComponent(labelRegis)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel2Layout.createSequentialGroup()
                        .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(isiPasswordR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(isiUsernameR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(isiEmailR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(isiNamaR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80))))
        );
        mainPanel2Layout.setVerticalGroup(
            mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelRegis)
                .addGap(18, 18, 18)
                .addComponent(isiNamaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isiEmailR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isiUsernameR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isiPasswordR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(buttonRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linkR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout background2Layout = new javax.swing.GroupLayout(background2);
        background2.setLayout(background2Layout);
        background2Layout.setHorizontalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background2Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(mainPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        background2Layout.setVerticalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(mainPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RegisterPLayout = new javax.swing.GroupLayout(RegisterP);
        RegisterP.setLayout(RegisterPLayout);
        RegisterPLayout.setHorizontalGroup(
            RegisterPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );
        RegisterPLayout.setVerticalGroup(
            RegisterPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background2, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        getContentPane().add(RegisterP, "RegisterC");

        background3.setPic("bgW.png");

        mainPanel3.setOpaque(false);

        labelWelcome.setBackground(new java.awt.Color(0, 0, 0));
        labelWelcome.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        labelWelcome.setForeground(new java.awt.Color(0, 0, 0));
        labelWelcome.setText("YouthWellness");

        labelSuccess.setBackground(new java.awt.Color(0, 0, 0));
        labelSuccess.setFont(new java.awt.Font("Cambria Math", 0, 9)); // NOI18N
        labelSuccess.setForeground(new java.awt.Color(0, 0, 0));
        labelSuccess.setText("Nurturing Minds, Inspiring Futures: Empowering Student Success!");

        buttonMulaiK.setBackground(new java.awt.Color(102, 102, 102));
        buttonMulaiK.setForeground(new java.awt.Color(255, 255, 255));
        buttonMulaiK.setText("Mulai Konseling");
        buttonMulaiK.setBackgroundColor("#5271ff");
        buttonMulaiK.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        buttonMulaiK.setMaximumSize(new java.awt.Dimension(151, 24));
        buttonMulaiK.setMinimumSize(new java.awt.Dimension(151, 24));
        buttonMulaiK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMulaiKActionPerformed(evt);
            }
        });

        buttonQuiz.setBackground(new java.awt.Color(102, 102, 102));
        buttonQuiz.setForeground(new java.awt.Color(255, 255, 255));
        buttonQuiz.setText("Quiz");
        buttonQuiz.setBackgroundColor("#5E17EB");
        buttonQuiz.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        buttonQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuizActionPerformed(evt);
            }
        });

        linkW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkWActionPerformed(evt);
            }
        });

        profilePicW.setOpaque(false);

        buttonName.setForeground(new java.awt.Color(0, 0, 0));
        buttonName.setText("Shinta Aiko");
        buttonName.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        buttonName.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        buttonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profilePicWLayout = new javax.swing.GroupLayout(profilePicW);
        profilePicW.setLayout(profilePicWLayout);
        profilePicWLayout.setHorizontalGroup(
            profilePicWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePicWLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(buttonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        profilePicWLayout.setVerticalGroup(
            profilePicWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePicWLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(buttonName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanel3Layout = new javax.swing.GroupLayout(mainPanel3);
        mainPanel3.setLayout(mainPanel3Layout);
        mainPanel3Layout.setHorizontalGroup(
            mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel3Layout.createSequentialGroup()
                .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addComponent(profilePicW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanel3Layout.createSequentialGroup()
                        .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(labelSuccess))
                            .addGroup(mainPanel3Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(buttonMulaiK, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanel3Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(buttonQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanel3Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(linkW, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanel3Layout.setVerticalGroup(
            mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profilePicW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSuccess)
                .addGap(51, 51, 51)
                .addComponent(buttonMulaiK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(linkW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout background3Layout = new javax.swing.GroupLayout(background3);
        background3.setLayout(background3Layout);
        background3Layout.setHorizontalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(mainPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        background3Layout.setVerticalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background3Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(mainPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout WelcomePLayout = new javax.swing.GroupLayout(WelcomeP);
        WelcomeP.setLayout(WelcomePLayout);
        WelcomePLayout.setHorizontalGroup(
            WelcomePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WelcomePLayout.setVerticalGroup(
            WelcomePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(WelcomeP, "WelcomeC");

        background4.setPic("bgLK.png");

        mainPanel4.setOpaque(false);

        linkLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkLKActionPerformed(evt);
            }
        });

        TitleKonseling.setBackground(new java.awt.Color(0, 0, 0));
        TitleKonseling.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        TitleKonseling.setForeground(new java.awt.Color(0, 0, 0));
        TitleKonseling.setText("Lakukan Konseling");

        boxKonselor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Pilih Konselor>", "Pria", "Wanita" }));

        boxHari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Pilih Hari Konseling>", "Pria", "Wanita" }));

        boxJam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Pilih Jam Konseling>", "Pria", "Wanita" }));

        buttonHub.setBackground(new java.awt.Color(102, 102, 102));
        buttonHub.setForeground(new java.awt.Color(255, 255, 255));
        buttonHub.setText("Hubungi Konselor");
        buttonHub.setBackgroundColor("#5271ff");
        buttonHub.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        buttonHub.setMaximumSize(new java.awt.Dimension(151, 24));
        buttonHub.setMinimumSize(new java.awt.Dimension(151, 24));
        buttonHub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanel4Layout = new javax.swing.GroupLayout(mainPanel4);
        mainPanel4.setLayout(mainPanel4Layout);
        mainPanel4Layout.setHorizontalGroup(
            mainPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mainPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanel4Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(buttonHub, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boxHari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxJam, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(linkLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TitleKonseling)
                        .addComponent(boxKonselor, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(359, Short.MAX_VALUE))
        );
        mainPanel4Layout.setVerticalGroup(
            mainPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TitleKonseling)
                .addGap(30, 30, 30)
                .addComponent(boxKonselor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boxHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boxJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonHub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(100, 100, 100)
                .addComponent(linkLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout background4Layout = new javax.swing.GroupLayout(background4);
        background4.setLayout(background4Layout);
        background4Layout.setHorizontalGroup(
            background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background4Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(mainPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        background4Layout.setVerticalGroup(
            background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background4Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(mainPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MulaiKPLayout = new javax.swing.GroupLayout(MulaiKP);
        MulaiKP.setLayout(MulaiKPLayout);
        MulaiKPLayout.setHorizontalGroup(
            MulaiKPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MulaiKPLayout.setVerticalGroup(
            MulaiKPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(MulaiKP, "MulaiKC");

        background5.setBlur(mainPanel5);

        mainPanel5.setOpaque(false);

        javax.swing.GroupLayout mainPanel5Layout = new javax.swing.GroupLayout(mainPanel5);
        mainPanel5.setLayout(mainPanel5Layout);
        mainPanel5Layout.setHorizontalGroup(
            mainPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        mainPanel5Layout.setVerticalGroup(
            mainPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout background5Layout = new javax.swing.GroupLayout(background5);
        background5.setLayout(background5Layout);
        background5Layout.setHorizontalGroup(
            background5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background5Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(mainPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        background5Layout.setVerticalGroup(
            background5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background5Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(mainPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BioKonPLayout = new javax.swing.GroupLayout(BioKonP);
        BioKonP.setLayout(BioKonPLayout);
        BioKonPLayout.setHorizontalGroup(
            BioKonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BioKonPLayout.setVerticalGroup(
            BioKonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(BioKonP, "BioKonC");

        background6.setPic("bgFB.png");

        mainPanel6.setOpaque(false);

        TitleFB.setBackground(new java.awt.Color(0, 0, 0));
        TitleFB.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        TitleFB.setForeground(new java.awt.Color(0, 0, 0));
        TitleFB.setText("Feedback");

        labelTulisFB.setBackground(new java.awt.Color(0, 0, 0));
        labelTulisFB.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        labelTulisFB.setForeground(new java.awt.Color(0, 0, 0));
        labelTulisFB.setText("Tulis Feedback");

        labelTopFB.setBackground(new java.awt.Color(0, 0, 0));
        labelTopFB.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        labelTopFB.setForeground(new java.awt.Color(0, 0, 0));
        labelTopFB.setText("Top Feedback");

        cardPanel.setOpaque(false);
        cardPanel.setLayout(new java.awt.CardLayout());

        c1.setColumns(20);
        c1.setRows(5);
        c1.setText("Hello");
        cardPanel.add(c1, "c1");

        c2.setColumns(20);
        c2.setRows(5);
        c2.setText("Konselor Baik");
        cardPanel.add(c2, "c2");

        c3.setColumns(20);
        c3.setRows(5);
        c3.setText("Aplikasi Bagus");
        c3.setToolTipText("");
        cardPanel.add(c3, "c3");

        c4.setColumns(20);
        c4.setRows(5);
        c4.setText("gwenchana");
        cardPanel.add(c4, "c4");

        c5.setColumns(20);
        c5.setRows(5);
        c5.setText("seru");
        c5.setToolTipText("");
        cardPanel.add(c5, "c5");

        buttonFeedback.setBackground(new java.awt.Color(102, 102, 102));
        buttonFeedback.setForeground(new java.awt.Color(255, 255, 255));
        buttonFeedback.setText("Kirim Feedback");
        buttonFeedback.setBackgroundColor("#5E17EB");
        buttonFeedback.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        buttonFeedback.setMaximumSize(new java.awt.Dimension(151, 24));
        buttonFeedback.setMinimumSize(new java.awt.Dimension(151, 24));
        buttonFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFeedbackActionPerformed(evt);
            }
        });

        buttonPrev.setBackground(new java.awt.Color(102, 102, 102));
        buttonPrev.setForeground(new java.awt.Color(255, 255, 255));
        buttonPrev.setText("Prev");
        buttonPrev.setBackgroundColor("#5271ff");
        buttonPrev.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        buttonPrev.setMaximumSize(new java.awt.Dimension(151, 24));
        buttonPrev.setMinimumSize(new java.awt.Dimension(151, 24));
        buttonPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrevActionPerformed(evt);
            }
        });

        buttonNext.setBackground(new java.awt.Color(102, 102, 102));
        buttonNext.setForeground(new java.awt.Color(255, 255, 255));
        buttonNext.setText("Next");
        buttonNext.setBackgroundColor("#5271ff");
        buttonNext.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        buttonNext.setMaximumSize(new java.awt.Dimension(151, 24));
        buttonNext.setMinimumSize(new java.awt.Dimension(151, 24));
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        linkF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkFActionPerformed(evt);
            }
        });

        isiFB.setBackground(new java.awt.Color(217, 217, 217));
        isiFB.setColumns(20);
        isiFB.setForeground(new java.awt.Color(0, 0, 0));
        isiFB.setRows(5);

        javax.swing.GroupLayout mainPanel6Layout = new javax.swing.GroupLayout(mainPanel6);
        mainPanel6.setLayout(mainPanel6Layout);
        mainPanel6Layout.setHorizontalGroup(
            mainPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mainPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleFB)
                    .addComponent(linkF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanel6Layout.createSequentialGroup()
                        .addGroup(mainPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(labelTulisFB)
                            .addComponent(isiFB, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(68, 68, 68)
                        .addGroup(mainPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTopFB))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        mainPanel6Layout.setVerticalGroup(
            mainPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(TitleFB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel6Layout.createSequentialGroup()
                        .addComponent(labelTulisFB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isiFB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel6Layout.createSequentialGroup()
                        .addComponent(labelTopFB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67)
                .addComponent(linkF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout background6Layout = new javax.swing.GroupLayout(background6);
        background6.setLayout(background6Layout);
        background6Layout.setHorizontalGroup(
            background6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background6Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(mainPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        background6Layout.setVerticalGroup(
            background6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background6Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(mainPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FeedbackPLayout = new javax.swing.GroupLayout(FeedbackP);
        FeedbackP.setLayout(FeedbackPLayout);
        FeedbackPLayout.setHorizontalGroup(
            FeedbackPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FeedbackPLayout.setVerticalGroup(
            FeedbackPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(FeedbackP, "FeedbackC");

        background7.setPic("bgBM.png");

        mainPanel7.setOpaque(false);

        profilePicBM.setOpaque(false);
        profilePicBM.setPic("C:\\Users\\dhafa\\Downloads\\Java Codes\\YouthWellness\\src\\Background\\imgPic.png");

        javax.swing.GroupLayout profilePicBMLayout = new javax.swing.GroupLayout(profilePicBM);
        profilePicBM.setLayout(profilePicBMLayout);
        profilePicBMLayout.setHorizontalGroup(
            profilePicBMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        profilePicBMLayout.setVerticalGroup(
            profilePicBMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        TitleNama.setBackground(new java.awt.Color(0, 0, 0));
        TitleNama.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        TitleNama.setForeground(new java.awt.Color(0, 0, 0));
        TitleNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleNama.setText("Shinta Aiko");

        buttonUbahProfil.setBackground(new java.awt.Color(102, 102, 102));
        buttonUbahProfil.setText("Ubah Profil");
        buttonUbahProfil.setBackgroundColor("#DFDFDF");
        buttonUbahProfil.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        buttonUbahProfil.setMaximumSize(new java.awt.Dimension(151, 24));
        buttonUbahProfil.setMinimumSize(new java.awt.Dimension(151, 24));
        buttonUbahProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahProfilActionPerformed(evt);
            }
        });

        buttonKeluarAkun.setBackground(new java.awt.Color(102, 102, 102));
        buttonKeluarAkun.setForeground(new java.awt.Color(255, 255, 255));
        buttonKeluarAkun.setText("Keluar Akun");
        buttonKeluarAkun.setBackgroundColor("#5E17EB");
        buttonKeluarAkun.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        buttonKeluarAkun.setMaximumSize(new java.awt.Dimension(151, 24));
        buttonKeluarAkun.setMinimumSize(new java.awt.Dimension(151, 24));
        buttonKeluarAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarAkunActionPerformed(evt);
            }
        });

        linkBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkBMActionPerformed(evt);
            }
        });

        labelEmailBM.setBackground(new java.awt.Color(0, 0, 0));
        labelEmailBM.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        labelEmailBM.setForeground(new java.awt.Color(51, 51, 51));
        labelEmailBM.setText("Email");

        TitleEmailBM.setBackground(new java.awt.Color(0, 0, 0));
        TitleEmailBM.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        TitleEmailBM.setForeground(new java.awt.Color(0, 0, 0));
        TitleEmailBM.setText("Shinaiko@gmail.com");

        labelUserNameBM.setBackground(new java.awt.Color(0, 0, 0));
        labelUserNameBM.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        labelUserNameBM.setForeground(new java.awt.Color(51, 51, 51));
        labelUserNameBM.setText("Username");

        TitleUNameBM.setBackground(new java.awt.Color(0, 0, 0));
        TitleUNameBM.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        TitleUNameBM.setForeground(new java.awt.Color(0, 0, 0));
        TitleUNameBM.setText("Meowko");

        labelNoTelpBM.setBackground(new java.awt.Color(0, 0, 0));
        labelNoTelpBM.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        labelNoTelpBM.setForeground(new java.awt.Color(51, 51, 51));
        labelNoTelpBM.setText("No Telp");

        TitleNoTelpBM.setBackground(new java.awt.Color(0, 0, 0));
        TitleNoTelpBM.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        TitleNoTelpBM.setForeground(new java.awt.Color(0, 0, 0));
        TitleNoTelpBM.setText("-");

        labelAlamatBM.setBackground(new java.awt.Color(0, 0, 0));
        labelAlamatBM.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        labelAlamatBM.setForeground(new java.awt.Color(51, 51, 51));
        labelAlamatBM.setText("Alamat");

        TitleAlamatBM.setBackground(new java.awt.Color(0, 0, 0));
        TitleAlamatBM.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        TitleAlamatBM.setForeground(new java.awt.Color(0, 0, 0));
        TitleAlamatBM.setText("-");

        labelBioBM.setBackground(new java.awt.Color(0, 0, 0));
        labelBioBM.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        labelBioBM.setForeground(new java.awt.Color(51, 51, 51));
        labelBioBM.setText("Bio");

        TitleBioBM.setEditable(false);
        TitleBioBM.setBackground(new java.awt.Color(217, 217, 217));
        TitleBioBM.setColumns(20);
        TitleBioBM.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        TitleBioBM.setForeground(new java.awt.Color(0, 0, 0));
        TitleBioBM.setRows(5);
        TitleBioBM.setText("-");
        TitleBioBM.setOpaque(false);

        javax.swing.GroupLayout mainPanel7Layout = new javax.swing.GroupLayout(mainPanel7);
        mainPanel7.setLayout(mainPanel7Layout);
        mainPanel7Layout.setHorizontalGroup(
            mainPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel7Layout.createSequentialGroup()
                .addGroup(mainPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(linkBM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanel7Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(mainPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonKeluarAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonUbahProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanel7Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(mainPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TitleNama)
                                    .addComponent(profilePicBM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(98, 98, 98)
                .addGroup(mainPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAlamatBM)
                    .addComponent(labelEmailBM)
                    .addComponent(TitleEmailBM, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNoTelpBM)
                    .addComponent(TitleNoTelpBM, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBioBM)
                    .addComponent(TitleAlamatBM, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUserNameBM)
                    .addComponent(TitleUNameBM, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitleBioBM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        mainPanel7Layout.setVerticalGroup(
            mainPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel7Layout.createSequentialGroup()
                .addGroup(mainPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(mainPanel7Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(labelEmailBM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TitleEmailBM)
                        .addGap(18, 18, 18)
                        .addComponent(labelUserNameBM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TitleUNameBM)
                        .addGap(18, 18, 18)
                        .addComponent(labelNoTelpBM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TitleNoTelpBM)
                        .addGap(18, 18, 18)
                        .addComponent(labelAlamatBM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TitleAlamatBM)
                        .addGap(18, 18, 18)
                        .addComponent(labelBioBM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TitleBioBM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(mainPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(profilePicBM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TitleNama)
                        .addGap(45, 45, 45)
                        .addComponent(buttonUbahProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonKeluarAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(linkBM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout background7Layout = new javax.swing.GroupLayout(background7);
        background7.setLayout(background7Layout);
        background7Layout.setHorizontalGroup(
            background7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background7Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(mainPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        background7Layout.setVerticalGroup(
            background7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background7Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(mainPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BioMahPLayout = new javax.swing.GroupLayout(BioMahP);
        BioMahP.setLayout(BioMahPLayout);
        BioMahPLayout.setHorizontalGroup(
            BioMahPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BioMahPLayout.setVerticalGroup(
            BioMahPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(BioMahP, "BioMahC");

        background8.setPic("bgUP.png");

        mainPanel8.setOpaque(false);

        TitleUP.setBackground(new java.awt.Color(0, 0, 0));
        TitleUP.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        TitleUP.setForeground(new java.awt.Color(0, 0, 0));
        TitleUP.setText("Ubah Profil");

        labelNama.setBackground(new java.awt.Color(0, 0, 0));
        labelNama.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        labelNama.setForeground(new java.awt.Color(0, 0, 0));
        labelNama.setText("Nama Lengkap");

        labelEmail.setBackground(new java.awt.Color(0, 0, 0));
        labelEmail.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(0, 0, 0));
        labelEmail.setText("Email");

        labelNoTelp.setBackground(new java.awt.Color(0, 0, 0));
        labelNoTelp.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        labelNoTelp.setForeground(new java.awt.Color(0, 0, 0));
        labelNoTelp.setText("Nomor Telpon");

        labelAlamat.setBackground(new java.awt.Color(0, 0, 0));
        labelAlamat.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        labelAlamat.setForeground(new java.awt.Color(0, 0, 0));
        labelAlamat.setText("Alamat");

        labelBio.setBackground(new java.awt.Color(0, 0, 0));
        labelBio.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        labelBio.setForeground(new java.awt.Color(0, 0, 0));
        labelBio.setText("Bio");

        labelGender.setBackground(new java.awt.Color(0, 0, 0));
        labelGender.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        labelGender.setForeground(new java.awt.Color(0, 0, 0));
        labelGender.setText("Jenis Kelamin");

        isiBioUP.setColumns(20);
        isiBioUP.setRows(5);

        isiGenderUP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Pilih>", "Pria", "Wanita" }));

        buttonSimpanPer.setBackground(new java.awt.Color(102, 102, 102));
        buttonSimpanPer.setForeground(new java.awt.Color(255, 255, 255));
        buttonSimpanPer.setText("Simpan Perubahan");
        buttonSimpanPer.setBackgroundColor("#5E17EB");
        buttonSimpanPer.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        buttonSimpanPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanPerActionPerformed(evt);
            }
        });

        buttonUbahFoto.setBackground(new java.awt.Color(102, 102, 102));
        buttonUbahFoto.setForeground(new java.awt.Color(255, 255, 255));
        buttonUbahFoto.setText("Ubah Foto Profil");
        buttonUbahFoto.setBackgroundColor("#5271ff");
        buttonUbahFoto.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        buttonUbahFoto.setMaximumSize(new java.awt.Dimension(151, 24));
        buttonUbahFoto.setMinimumSize(new java.awt.Dimension(151, 24));
        buttonUbahFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanel8Layout = new javax.swing.GroupLayout(mainPanel8);
        mainPanel8.setLayout(mainPanel8Layout);
        mainPanel8Layout.setHorizontalGroup(
            mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonSimpanPer, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(labelEmail)
                    .addComponent(TitleUP)
                    .addComponent(labelNama)
                    .addComponent(labelAlamat)
                    .addComponent(labelNoTelp)
                    .addComponent(isiNamaUP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(isiEmailUP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(isiNoTelpUP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(isiAlamatUP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonUbahFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(mainPanel8Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBio)
                            .addComponent(labelGender)
                            .addComponent(isiGenderUP, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isiBioUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))))
        );
        mainPanel8Layout.setVerticalGroup(
            mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TitleUP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanel8Layout.createSequentialGroup()
                        .addGroup(mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNama)
                            .addComponent(labelBio))
                        .addGap(7, 7, 7)
                        .addComponent(isiNamaUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isiEmailUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(isiBioUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel8Layout.createSequentialGroup()
                        .addComponent(labelNoTelp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isiNoTelpUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanel8Layout.createSequentialGroup()
                        .addComponent(labelGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isiGenderUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, Short.MAX_VALUE)
                .addComponent(labelAlamat)
                .addGap(3, 3, 3)
                .addGroup(mainPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUbahFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isiAlamatUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonSimpanPer, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout background8Layout = new javax.swing.GroupLayout(background8);
        background8.setLayout(background8Layout);
        background8Layout.setHorizontalGroup(
            background8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background8Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(mainPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        background8Layout.setVerticalGroup(
            background8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background8Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(mainPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout UbahProfilPLayout = new javax.swing.GroupLayout(UbahProfilP);
        UbahProfilP.setLayout(UbahProfilPLayout);
        UbahProfilPLayout.setHorizontalGroup(
            UbahProfilPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UbahProfilPLayout.setVerticalGroup(
            UbahProfilPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(UbahProfilP, "UbahProfilC");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        background.add(mainPanel);
        mainPanel.setBounds(30, 240, 100, 100);

        javax.swing.GroupLayout mpanelLayout = new javax.swing.GroupLayout(mpanel);
        mpanel.setLayout(mpanelLayout);
        mpanelLayout.setHorizontalGroup(
            mpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        mpanelLayout.setVerticalGroup(
            mpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        getContentPane().add(mpanel, "card4");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignInActionPerformed
        // TODO add your handling code here:
        CpassL = isiPasswordL.getPassword();
        passL = new String(CpassL);
        if((isiEmailUsernameL.getText().equals(email) || isiEmailUsernameL.getText().equals(uName)) 
            && passL.equals(pass)){
            
            isiEmailUsernameL.setText("");
            isiPasswordL.setText("");
            
            CardLayout contentPane = (CardLayout) getContentPane().getLayout();
            contentPane.show(getContentPane(), "WelcomeC");
        }
        
    }//GEN-LAST:event_buttonSignInActionPerformed

    private void linkLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkLActionPerformed
        // TODO add your handling code here:
         
        isiEmailUsernameL.setText("");
        isiPasswordL.setText("");
        
        CardLayout contentPane = (CardLayout) getContentPane().getLayout();
        contentPane.show(getContentPane(), "RegisterC");
    }//GEN-LAST:event_linkLActionPerformed

    private void buttonRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisActionPerformed
        // TODO add your handling code here:
        namaL = isiNamaR.getText();
        email = isiEmailR.getText();
        uName = isiUsernameR.getText();
        pass = isiPasswordR.getText();
        
        if (checR.isSelected() && !namaL.equals("") && 
            !uName.equals("") && !pass.equals("")) {
            
            TitleNama.setText(namaL);
            buttonName.setText(namaL);
            TitleEmailBM.setText(email);
            TitleUNameBM.setText(uName);
            
            JTextField[] textFields = {isiNamaR, isiPasswordR, isiEmailR, isiUsernameR};

            for (JTextField textField : textFields) {
                textField.setText("");
            }
            checR.setSelected(false);
            
            CardLayout contentPane = (CardLayout) getContentPane().getLayout();
            contentPane.show(getContentPane(), "LoginC");
        }
    }//GEN-LAST:event_buttonRegisActionPerformed

    private void linkRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkRActionPerformed
        // TODO add your handling code here:
        JTextField[] textFields = {isiNamaR, isiPasswordR, isiEmailR, isiUsernameR};

        for (JTextField textField : textFields) {
            textField.setText("");
        }
        checR.setSelected(false);
        
        CardLayout contentPane = (CardLayout) getContentPane().getLayout();
        contentPane.show(getContentPane(), "LoginC");
    }//GEN-LAST:event_linkRActionPerformed

    private void buttonMulaiKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMulaiKActionPerformed
        // TODO add your handling code here:
        CardLayout contentPane = (CardLayout) getContentPane().getLayout();
        contentPane.show(getContentPane(), "MulaiKC");
    }//GEN-LAST:event_buttonMulaiKActionPerformed

    private void buttonQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuizActionPerformed
        // TODO add your handling code here:
        
        try {
            // Specify the URL you want to open
            URI uri = new URI("https://github.com/Dhafanur25/TugasBesarRPL");

            // Check if the Desktop class is supported (works on Windows, Linux, and macOS)
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().browse(uri);
            } else {
                // If Desktop is not supported, you can open the link in another way.
                // For example, you can use the ProcessBuilder to open the default web browser.
            }
        }catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_buttonQuizActionPerformed

    private void linkWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkWActionPerformed
        // TODO add your handling code here:
        CardLayout contentPane = (CardLayout) getContentPane().getLayout();
        contentPane.show(getContentPane(), "FeedbackC");
    }//GEN-LAST:event_linkWActionPerformed

    private void buttonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNameActionPerformed
        // TODO add your handling code here:
        CardLayout contentPane = (CardLayout) getContentPane().getLayout();
        contentPane.show(getContentPane(), "BioMahC");
    }//GEN-LAST:event_buttonNameActionPerformed

    private void linkLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkLKActionPerformed
        // TODO add your handling code here:
        boxKonselor.setSelectedItem("<Pilih Konselor>");
        boxHari.setSelectedItem("<Pilih Hari Konseling>");
        boxJam.setSelectedItem("<Pilih Jam Konseling>");
        CardLayout contentPane = (CardLayout) getContentPane().getLayout();
        contentPane.show(getContentPane(), "WelcomeC");
    }//GEN-LAST:event_linkLKActionPerformed

    private void buttonHubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHubActionPerformed
        // TODO add your handling code here:
        boxKonselor.setSelectedItem("<Pilih Konselor>");
        boxHari.setSelectedItem("<Pilih Hari Konseling>");
        boxJam.setSelectedItem("<Pilih Jam Konseling>");
        CardLayout contentPane = (CardLayout) getContentPane().getLayout();
        contentPane.show(getContentPane(), "BioKonC");
    }//GEN-LAST:event_buttonHubActionPerformed

    private void buttonFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFeedbackActionPerformed
        // TODO add your handling code here:
        isiFB.setText("");
    }//GEN-LAST:event_buttonFeedbackActionPerformed

    private void buttonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrevActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardLayout.previous(cardPanel);
    }//GEN-LAST:event_buttonPrevActionPerformed

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardLayout.next(cardPanel);
    }//GEN-LAST:event_buttonNextActionPerformed

    private void linkFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkFActionPerformed
        // TODO add your handling code here:
        isiFB.setText("");
        CardLayout contentPane = (CardLayout) getContentPane().getLayout();
        contentPane.show(getContentPane(), "WelcomeC");
    }//GEN-LAST:event_linkFActionPerformed

    private void buttonUbahProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahProfilActionPerformed
        // TODO add your handling code here:
        CardLayout contentPane = (CardLayout) getContentPane().getLayout();
        contentPane.show(getContentPane(), "UbahProfilC");
    }//GEN-LAST:event_buttonUbahProfilActionPerformed

    private void buttonKeluarAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarAkunActionPerformed
        // TODO add your handling code here:
        QSure x = new QSure(this);
        x.setVisible(true);
    }//GEN-LAST:event_buttonKeluarAkunActionPerformed

    private void linkBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkBMActionPerformed
        // TODO add your handling code here:

        CardLayout contentPane = (CardLayout) getContentPane().getLayout();
        contentPane.show(getContentPane(), "WelcomeC");
    }//GEN-LAST:event_linkBMActionPerformed
    private void updateUIComponentIfNotEmpty(JTextField textField, JLabel label, JButton button) {
        String text = textField.getText().trim();
        if (!text.isEmpty()) {
            label.setText(text);
            if (button != null) {
                button.setText(text);
            }
        }
    }
    private void buttonSimpanPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanPerActionPerformed
        // TODO add your handling code here:
        
        if (filePath != null){
            profilePicBM.setPic(filePath);
            profilePicW.setPic(filePath);
        }
    
        updateUIComponentIfNotEmpty(isiNamaUP, TitleNama, buttonName);
        updateUIComponentIfNotEmpty(isiEmailUP, TitleEmailBM, null); 
        updateUIComponentIfNotEmpty(isiNoTelpUP, TitleNoTelpBM, null); 
        updateUIComponentIfNotEmpty(isiAlamatUP, TitleAlamatBM, null);
        if (!isiBioUP.getText().equals("")){
            TitleBioBM.setText(isiBioUP.getText());
        }

        isiBioUP.setText("");
        JTextField[] textFields = {isiNamaUP, isiEmailUP, isiNoTelpUP, isiAlamatUP};

        for (JTextField textField : textFields) {
            textField.setText("");
        }
        
        isiGenderUP.setSelectedItem("<Pilih>");
        
        CardLayout contentPane = (CardLayout) getContentPane().getLayout();
        contentPane.show(getContentPane(), "BioMahC");
        

    }//GEN-LAST:event_buttonSimpanPerActionPerformed

    private void buttonUbahFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahFotoActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnValue = fileChooser.showOpenDialog(this);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            filePath = selectedFile.getAbsolutePath();
        }
        
    }//GEN-LAST:event_buttonUbahFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BioKonP;
    private javax.swing.JPanel BioMahP;
    private javax.swing.JPanel FeedbackP;
    private javax.swing.JPanel LoginP;
    private javax.swing.JPanel MulaiKP;
    private javax.swing.JPanel RegisterP;
    private javax.swing.JLabel TitleAlamatBM;
    private javax.swing.JTextArea TitleBioBM;
    private javax.swing.JLabel TitleEmailBM;
    private javax.swing.JLabel TitleFB;
    private javax.swing.JLabel TitleKonseling;
    private javax.swing.JLabel TitleNama;
    private javax.swing.JLabel TitleNoTelpBM;
    private javax.swing.JLabel TitleUNameBM;
    private javax.swing.JLabel TitleUP;
    private javax.swing.JPanel UbahProfilP;
    private javax.swing.JPanel WelcomeP;
    private Background.Background background;
    private Background.BackgroundRL background1;
    private Background.BackgroundRL background2;
    private Background.Background background3;
    private Background.Background background4;
    private Background.Background background5;
    private Background.Background background6;
    private Background.Background background7;
    private Background.Background background8;
    private swing.RoundComboBox boxHari;
    private swing.RoundComboBox boxJam;
    private swing.RoundComboBox boxKonselor;
    private swing.RoundButton buttonFeedback;
    private swing.RoundButton buttonHub;
    private swing.RoundButton buttonKeluarAkun;
    private swing.RoundButton buttonMulaiK;
    private swing.TransparentButton buttonName;
    private swing.RoundButton buttonNext;
    private swing.RoundButton buttonPrev;
    private swing.RoundButton buttonQuiz;
    private swing.CoolButton buttonRegis;
    private swing.CoolButton buttonSignIn;
    private swing.RoundButton buttonSimpanPer;
    private swing.RoundButton buttonUbahFoto;
    private swing.RoundButton buttonUbahProfil;
    private swing.LabelArea c1;
    private swing.LabelArea c2;
    private swing.LabelArea c3;
    private swing.LabelArea c4;
    private swing.LabelArea c5;
    private javax.swing.JPanel cardPanel;
    private swing.CoolCheckBox checR;
    private swing.RoundTextField isiAlamatUP;
    private swing.RoundTextArea isiBioUP;
    private swing.TextField isiEmailR;
    private swing.RoundTextField isiEmailUP;
    private swing.TextField isiEmailUsernameL;
    private javax.swing.JTextArea isiFB;
    private swing.RoundComboBox isiGenderUP;
    private swing.TextField isiNamaR;
    private swing.RoundTextField isiNamaUP;
    private swing.RoundTextField isiNoTelpUP;
    private swing.PasswordField isiPasswordL;
    private swing.TextField isiPasswordR;
    private swing.TextField isiUsernameR;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelAlamatBM;
    private javax.swing.JLabel labelBio;
    private javax.swing.JLabel labelBioBM;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmailBM;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNoTelp;
    private javax.swing.JLabel labelNoTelpBM;
    private javax.swing.JLabel labelRegis;
    private javax.swing.JLabel labelSuccess;
    private javax.swing.JLabel labelTopFB;
    private javax.swing.JLabel labelTulisFB;
    private javax.swing.JLabel labelUserNameBM;
    private javax.swing.JLabel labelWelcome;
    private swing.Link3 linkBM;
    private swing.Link3 linkF;
    private swing.Link1 linkL;
    private swing.Link3 linkLK;
    private swing.Link2 linkR;
    private swing.Link4 linkW;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainPanel1;
    private javax.swing.JPanel mainPanel2;
    private javax.swing.JPanel mainPanel3;
    private javax.swing.JPanel mainPanel4;
    private javax.swing.JPanel mainPanel5;
    private javax.swing.JPanel mainPanel6;
    private javax.swing.JPanel mainPanel7;
    private javax.swing.JPanel mainPanel8;
    private javax.swing.JPanel mpanel;
    public swing.ProfilePic profilePicBM;
    public swing.RightSideProfilePic profilePicW;
    // End of variables declaration//GEN-END:variables
}
